env:
  node: true
  mocha: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
rules:
  space-before-function-paren:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  no-extra-semi:
    - error
  eol-last:
    - error
  no-trailing-spaces:
    - error
