runtime: nodejs
env: flex
service: default
resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5
env_variables:
  GITHUB_SIGNATURE: GITHUB_SIGNATURE_HERE
  FIREBASE_DATABASE_URL: "https://rocket-ci.firebaseio.com"
  FIREBASE_SERVICE_ACCOUNT_PATH: "cred/trigger-build.json"

